from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
	HRFlowable,
	Paragraph,
	SimpleDocTemplate,
	Spacer,
	Table,
	TableStyle,
)

from app.models.ai_interpretation import AIInterpretation, RiskLevel
from app.models.medical_case import MedicalCase
from app.models.user import User

DISCLAIMER = (
	"MEDICAL DISCLAIMER: This report is generated by an AI system and is intended "
	"for informational purposes only. It does not constitute medical advice, diagnosis, "
	"or treatment. Always consult a qualified healthcare professional before making any "
	"medical decisions. ClinInsights is not liable for any actions taken based on this report."
)

STATUS_COLORS = {
	"normal": colors.HexColor("#1a7a4a"),
	"caution": colors.HexColor("#b45309"),
	"abnormal": colors.HexColor("#b91c1c"),
}

RISK_COLORS = {
	RiskLevel.LOW: colors.HexColor("#1a7a4a"),
	RiskLevel.MODERATE: colors.HexColor("#b45309"),
	RiskLevel.HIGH: colors.HexColor("#b91c1c"),
}


def _get_styles() -> dict:
	base = getSampleStyleSheet()
	return {
		"title": ParagraphStyle(
			"title",
			parent=base["Title"],
			fontSize=22,
			textColor=colors.HexColor("#1F4E79"),
			spaceAfter=4,
		),
		"subtitle": ParagraphStyle(
			"subtitle",
			parent=base["Normal"],
			fontSize=11,
			textColor=colors.HexColor("#555555"),
			spaceAfter=2,
		),
		"section": ParagraphStyle(
			"section",
			parent=base["Heading2"],
			fontSize=13,
			textColor=colors.HexColor("#1F4E79"),
			spaceBefore=14,
			spaceAfter=6,
		),
		"body": ParagraphStyle(
			"body",
			parent=base["Normal"],
			fontSize=10,
			textColor=colors.HexColor("#333333"),
			leading=16,
		),
		"disclaimer": ParagraphStyle(
			"disclaimer",
			parent=base["Normal"],
			fontSize=8,
			textColor=colors.HexColor("#888888"),
			leading=12,
		),
		"question": ParagraphStyle(
			"question",
			parent=base["Normal"],
			fontSize=10,
			textColor=colors.HexColor("#333333"),
			leftIndent=12,
			leading=16,
		),
	}


def generate_pdf(
	case: MedicalCase,
	interpretation: AIInterpretation,
	user: User | None,
) -> bytes:
	"""
	Generate a PDF summary of the AI interpretation for a medical case.

	Args:
		case: The MedicalCase record.
		interpretation: The AIInterpretation record.
		user: The authenticated user, or None for guests.

	Returns:
		Raw PDF bytes.
	"""
	buffer = BytesIO()
	doc = SimpleDocTemplate(
		buffer,
		pagesize=A4,
		rightMargin=20 * mm,
		leftMargin=20 * mm,
		topMargin=20 * mm,
		bottomMargin=20 * mm,
	)

	styles = _get_styles()
	story = []

	# ── Header ──────────────────────────────────────────────────────────────
	patient_name = f"{user.first_name} {user.last_name}".strip() if user else "Guest"
	upload_date = (
		interpretation.generated_at.strftime("%B %d, %Y at %H:%M UTC")
		if interpretation.generated_at
		else datetime.utcnow().strftime("%B %d, %Y")
	)

	story.append(Paragraph("ClinInsights", styles["title"]))
	story.append(Paragraph("AI Lab Result Interpretation Report", styles["subtitle"]))
	story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#2E75B6")))
	story.append(Spacer(1, 6 * mm))

	# ── Patient Info ─────────────────────────────────────────────────────────
	story.append(Paragraph("Patient Information", styles["section"]))
	info_data = [
		["Patient Name", patient_name],
		["Report Date", upload_date],
		["Case ID", str(case.id)],
		["Risk Level", (interpretation.risk_level.value.upper() if interpretation.risk_level else "N/A")],
		["Confidence", (interpretation.confidence.value.upper() if interpretation.confidence else "N/A")],
	]
	info_table = Table(info_data, colWidths=[50 * mm, 120 * mm])
	info_table.setStyle(
		TableStyle(
			[
				("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
				("FONTSIZE", (0, 0), (-1, -1), 10),
				("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
				("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1F4E79")),
				("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#333333")),
				("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#F5F8FC"), colors.white]),
				("TOPPADDING", (0, 0), (-1, -1), 6),
				("BOTTOMPADDING", (0, 0), (-1, -1), 6),
				("LEFTPADDING", (0, 0), (-1, -1), 8),
				("RIGHTPADDING", (0, 0), (-1, -1), 8),
				("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
			]
		)
	)
	story.append(info_table)
	story.append(Spacer(1, 4 * mm))

	# ── AI Summary ───────────────────────────────────────────────────────────
	if interpretation.summary:
		story.append(Paragraph("AI Summary", styles["section"]))
		story.append(Paragraph(interpretation.summary, styles["body"]))
		story.append(Spacer(1, 4 * mm))

	# ── Value Breakdown Table ────────────────────────────────────────────────
	if interpretation.value_breakdown:
		story.append(Paragraph("Lab Results Breakdown", styles["section"]))

		headers = ["Metric", "Value", "Unit", "Status"]
		rows = [headers]
		for item in interpretation.value_breakdown:
			rows.append(
				[
					item.metric or "",
					str(item.value) if item.value is not None else "",
					item.unit or "",
					(item.status or "").upper(),
				]
			)

		col_widths = [60 * mm, 30 * mm, 30 * mm, 35 * mm]
		breakdown_table = Table(rows, colWidths=col_widths)

		table_style = [
			("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
			("FONTSIZE", (0, 0), (-1, -1), 9),
			("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
			("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
			("ALIGN", (1, 0), (-1, -1), "CENTER"),
			("ALIGN", (0, 0), (0, -1), "LEFT"),
			("TOPPADDING", (0, 0), (-1, -1), 5),
			("BOTTOMPADDING", (0, 0), (-1, -1), 5),
			("LEFTPADDING", (0, 0), (-1, -1), 6),
			("RIGHTPADDING", (0, 0), (-1, -1), 6),
			("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
			("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F8FC")]),
		]

		# Color status column per value
		for row_idx, item in enumerate(interpretation.value_breakdown, start=1):
			status_key = (item.status or "").lower()
			color = STATUS_COLORS.get(status_key, colors.HexColor("#333333"))
			table_style.append(("TEXTCOLOR", (3, row_idx), (3, row_idx), color))
			table_style.append(("FONTNAME", (3, row_idx), (3, row_idx), "Helvetica-Bold"))

		breakdown_table.setStyle(TableStyle(table_style))
		story.append(breakdown_table)
		story.append(Spacer(1, 4 * mm))

	# ── Suggested Questions ──────────────────────────────────────────────────
	if interpretation.suggested_questions:
		story.append(Paragraph("Suggested Questions for Your Doctor", styles["section"]))
		for i, question in enumerate(interpretation.suggested_questions, start=1):
			story.append(Paragraph(f"{i}. {question}", styles["question"]))
		story.append(Spacer(1, 4 * mm))

	# ── Disclaimer ───────────────────────────────────────────────────────────
	story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CCCCCC")))
	story.append(Spacer(1, 3 * mm))
	story.append(Paragraph(DISCLAIMER, styles["disclaimer"]))

	doc.build(story)
	return buffer.getvalue()
