"""add title to medical_cases

Revision ID: 831ec080473c
Revises: 3f2a9f6e7b14
Create Date: 2026-05-29 08:19:49.314136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '831ec080473c'
down_revision: Union[str, Sequence[str], None] = '3f2a9f6e7b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_uploads_medical_case_id'), table_name='medical_uploads')
    op.drop_table('medical_uploads')
    op.drop_constraint(op.f('notification_medical_case_id_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'medical_cases', ['medical_case_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_medical_case_id_fkey'), 'notification', 'medical_cases', ['medical_case_id'], ['id'], ondelete='SET NULL')
    op.create_table('medical_uploads',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('medical_case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['medical_case_id'], ['medical_cases.id'], name=op.f('medical_uploads_medical_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('medical_uploads_pkey'))
    )
    op.create_index(op.f('ix_medical_uploads_medical_case_id'), 'medical_uploads', ['medical_case_id'], unique=False)
    # ### end Alembic commands ###
